# Generated by Django 5.0.7 on 2024-07-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Vaccinations',
            new_name='vaccinations',
        ),
    ]
